sudo: required
services:
    - required

before_install:
    - docker build -t navnit-sarda/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true navnit-sarda/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-testing"
    env: "DockerTesting-env"
    bucket_name: "elasticbeanstalk-us-east-2-633061176406"
    bucket_path: "docker-testing"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
        


